version: "3.8"

services: 
  mysql_trial:
    container_name: running-mysql-trial
    image: mysql
    environment: 
      MYSQL_DATABASE: koerber
      MYSQL_USER: Luiz
      MYSQL_PASSWORD: mysqldatabase
      MYSQL_ROOT_PASSWORD: mysqldatabase
      SERVICE_NAME: mysql_trial
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      start_period: 60s
      interval: 5s
      timeout: 5s
      retries: 5
    ports: 
      - 3306:3306
    expose:
      - 3306
    volumes:
      - "./back/db/db-init.script:/docker-entrypoint-initdb.d/0_init.sql"
    networks:
      - internalnet

  node-trial:
    container_name: running-server-trial
    restart: always
    build: 
      context: ./back
      dockerfile: Dockerfile
    ports: 
      - 7700:7700
    # expose:
    #   - 7700
    depends_on: 
      mysql_trial:
        condition: service_healthy
    networks:
      - internalnet

  vite-trial:
    container_name: running-ui-trial
    restart: always
    build: 
      context: ./front
      dockerfile: Dockerfile
    ports: 
      - 5173:5173
    expose:
      - 5173
    depends_on: 
      mysql_trial:
        condition: service_healthy
    networks:
      - internalnet

networks:
  internalnet:
     driver: bridge
